### PR TITLE
Fix sub space edit

### LINKED ISSUE #1403: an error message when try to edit a space
1.open a space you created in DEV or web stage ENV.
2.click the "edit" button
3.change one of the fields
4.click on "save changes" button

there is a message : "Something went wrong..."

https://web-dev.common.io/commons/7a7462c7-0e56-4a16-b644-0320c477cc09/edit

Image

(notion ticket [here](https://www.notion.so/daostack/4201345ffb58445492a763a647dbfcb5?v=e563b8cbb5474407bc6f7a938bf7a959&p=6cf7a32dc1184c82a3702b34554a38d9&pm=s) and [here](https://www.notion.so/daostack/Couldn-t-save-a-space-after-replacing-image-92b586cd55b34f369dc8f53e91a1aa62))

### PR DESCRIPTION
**Pull request by danielr18**
Closes https://github.com/daostack/common-web/issues/1403

### CODE REVIEW

File: functions/src/commons/services/update.ts [hunk 1]
```diff
@@ -16,14 +16,14 @@ export const update = async (payload: CommonUpdatePayload): Promise<CommonUpdate
     const common = await commonsDb.get(payload.commonId, true)
 
     if (payload.changes?.name && common.directParent?.commonId) {
-        const updatedName = payload.changes.name
-        const existingCommonWithName = await CommonsCollection
-            .orderBy("name")
-            .where("directParent.commonId", "==", common.directParent?.commonId)
-            .where("name", ">=", updatedName.toUpperCase())
-            .where("name", "<=", updatedName.toLowerCase() + "\uf8ff").get()
```
Comment (danielr18) [inline functions/src/commons/services/update.ts:24]: This doesn't seem to be working as expected.
See https://stackoverflow.com/a/62868285

**Comment by ariel-dao** [comment]
deployed to dev
