### PR TITLE
CM-1297 check old pending sellers

### LINKED ISSUE #1297: Create "verification failed" for PayMe sellers
We need a cron to check sellers in `pending` status after 7 days from creation date. (cron should run daily)

In the cron, check on PayMe if the seller is validated,
if the seller is validated, update it and omit `PAYME_SELLER_VALIDATION_APPROVED` as it is omitted in`payme/listener`. 

if the seller is not validated, remove `bankAccountDetails` (set to `null`) from the `seller` and emit a notification + email to prompt the user to re-upload the documents.

The documents need to be validated and sent through the same endpoint as it is sent when the user adds the bank account details, but there should be a variable to state that the update is also for the seller and not just the bank account details (default behavior).

When the seller documents are re-uploaded, they should be sent using `business/uploadSellerFiles`.

- known bug: `uploadSellerFiles` is pulling the bankAccountDetails from the bank account details collection and not from the seller, this should be fixed in this PR.

We also need a second cron similar to `checkInvoicesUploading` that will emit an event to prompt the user to re-upload the bank account details, add a `bankAccountDocsNotReuploadedNotificationsCounter` to funding proposal type to keep track. 
- Once the counter reaches 4, fail the proposal.

* Seller should have a status of `rejected due to bad bank account details` or something similar to indicated that the seller validation failed and is pending for new bank account details
* I think that the proposal funding process stage can be left at `PENDING_SELLER_APPROVAL`, if the user won't upload the docs for 4 weeks the proposal will just fail, and if the user will upload and the seller will be approved the proposal will continue.

### PR DESCRIPTION
**Pull request by noamso1**

### CODE REVIEW

**Comment by noamso1** [comment]
@ariel-dao Everything is done. still we need to create an email template for PAYME_SELLER_VALIDATION_WARNING

File: functions/src/discussionMessage/triggers.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ async function countDiscussionMessages(discussionMessage: IDiscussionMessage, v:
   }
   if ( commonId ) {
     try {
-      let common: ICommon = await commonsDb.get( commonId )
+      const common: ICommon = await commonsDb.get( commonId )
```
Comment (ariel-dao) [inline functions/src/discussionMessage/triggers.ts]: update only fields you need not all the entity

File: functions/src/discussionMessage/triggers.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ async function countDiscussionMessages(discussionMessage: IDiscussionMessage, v:
   const discussionId = discussionMessage.discussionId
   let commonId : string
   try {
-    let discussion: IDiscussion = await discussionDb.getDiscussion( discussionId )
+    const discussion: IDiscussion = await discussionDb.getDiscussion( discussionId )
     let x : number = discussion.messageCount; if ( !x ) x = 0
```
Comment (ariel-dao) [inline functions/src/discussionMessage/triggers.ts]: move `if` line

File: functions/src/discussionMessage/triggers.ts [hunk 3]
```diff
@@ -43,7 +43,7 @@ async function countDiscussionMessages(discussionMessage: IDiscussionMessage, v:
   }
   if ( commonId ) {
     try {
-      let common: ICommon = await commonsDb.get( commonId )
+      const common: ICommon = await commonsDb.get( commonId )
       let x : number = common.messageCount; if ( !x ) x = 0
```
Comment (ariel-dao) [inline functions/src/discussionMessage/triggers.ts]: move `if` line

File: functions/src/payments/business/payme/payOut/createSeller.ts [hunk 4]
```diff
@@ -59,17 +60,17 @@ export const createSeller = async (userId: string): Promise<ISeller> => {
...
+        seller.status = SELLER_STATUSES.PENDING;
         seller.lastError = '';
         seller.paymeSellerId = res.seller_payme_id;
     } else {
         seller.lastError = res.status_error_details;
-        seller.status = 'failed';
+        seller.status = SELLER_STATUSES.REJECTED;
     }
 
     await sellerDb.update(seller, userId);
```
Comment (ariel-dao) [inline functions/src/payments/business/payme/payOut/createSeller.ts]: update only selected fields not the entire entity

File: functions/src/payments/business/payme/payOut/uploadSellerFiles.ts [hunk 5]
```diff
@@ -7,12 +7,13 @@ import { uploadSellerFilesRequestValidationSchema } from '../../../../shared/sch
 import { sellerFileValidationSchema } from '../../../../shared/schemas/sellerFile';
 import { getClientKey } from '../../../providers/payme/utils';
 import { paymePayOutProvider } from '../../../providers/payme/payOut';
-import { BankAccountDetailsDb } from '../../../db/bankAccountDetails';
 import { ISeller } from '../../../../shared/interfaces/payments/payme/ISeller';
 
-export const uploadSellerFiles = async (seller: ISeller) => {
+export const uploadSellerFiles = async (seller: Partial<ISeller>) => {
+    if ( !seller.userId ) return
```
Comment (ariel-dao) [inline functions/src/payments/business/payme/payOut/uploadSellerFiles.ts]: throw errors

File: functions/src/payments/business/payme/payOut/uploadSellerFiles.ts [hunk 6]
```diff
@@ -7,12 +7,13 @@ import { uploadSellerFilesRequestValidationSchema } from '../../../../shared/sch
...
+    if ( !seller.paymeSellerId ) return
```
Comment (ariel-dao) [inline functions/src/payments/business/payme/payOut/uploadSellerFiles.ts]: throw errors

File: functions/src/payments/business/payme/payOut/uploadSellerFiles.ts [hunk 7]
```diff
@@ -7,12 +7,13 @@ import { uploadSellerFilesRequestValidationSchema } from '../../../../shared/sch
...
 
-    const { identificationDocs } = await BankAccountDetailsDb.get(seller.userId);
+    const identificationDocs = seller.bankAccountDetails.identificationDocs
     if (identificationDocs.length === 0) throw new NotImplementedError('The user has not any legal docs.');
```
Comment (ariel-dao) [inline functions/src/payments/business/payme/payOut/uploadSellerFiles.ts:18]: might want to add a log here (payout logs)

File: functions/src/payments/controllers/bankAccountDetails/updateBankAccountDetails.ts [hunk 8]
```diff
@@ -23,6 +25,10 @@ export const updateBankAccountDetails = async (req, res, next) =>
 
                 const seller = await sellerDb.get(userId);
```
Comment (ariel-dao) [inline functions/src/payments/controllers/bankAccountDetails/updateBankAccountDetails.ts:26]: what if seller is not found? maybe user the get "throws" to throw error?

File: functions/src/payments/crons/checkPendingSellerStatus.ts [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+import { ISeller } from '../../shared/interfaces/payments/payme/ISeller'
+import { SELLER_STATUSES } from '../../shared/enums/SELLER_STATUSES';
+import { firestore } from 'firebase-admin';
+import { BankAccountDetailsDb } from '../../payments/db/bankAccountDetails'
+import { createEvent } from '../../util/db/eventDbService';
+import { EVENT_TYPES } from '../../shared/enums/EVENT_TYPES';
+import { num } from '../../util/helpers/numeric'
+
+export const checkPendingSellerStatus = async () => {
+    const sellers = await sellerDb.getMany( { status: 'pending' } )
```
Comment (ariel-dao) [inline functions/src/payments/crons/checkPendingSellerStatus.ts]: enum

File: functions/src/payments/crons/checkPendingSellerStatus.ts [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+                await sellerDb.update(sellerUpdate, userId)
+                await createEvent( { userId, type: EVENT_TYPES.PAYME_SELLER_VALIDATION_WARNING } );
+                
+            } else {
+                // clear seller.bankAccountDetails
+                const sellerUpdate: Partial<ISeller> = {
+                    id: seller.id,
+                    status: SELLER_STATUSES.REJECTED,
+                    warningCounter: warn,
+                    bankAccountDetails: { userId }
```
Comment (ariel-dao) [inline functions/src/payments/crons/checkPendingSellerStatus.ts:51]: why save only userId on details and not empty object?

File: functions/src/payments/crons/checkPendingSellerStatus.ts [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+                }
+                sellerDb.update(sellerUpdate, userId)
+    
+                // clear bankAccount identification docs
```
Comment (ariel-dao) [inline functions/src/payments/crons/checkPendingSellerStatus.ts:55]: should clear all of the bank account details nor just id docs

File: functions/src/payments/db/sellers/getSeller.ts [hunk 12]
```diff
@@ -22,6 +22,10 @@ export const getSeller = async ({ userId, sellerId }: IGetSellerArgs, throwErr =
       throw new NotFoundError(sellerId, 'seller');
     }
 
+    if (!seller) {
```
Comment (ariel-dao) [inline functions/src/payments/db/sellers/getSeller.ts:25]: remove, if seller doesnt exist it will return null anyway

File: functions/src/payments/db/sellers/getSellers.ts [hunk 13]
```diff
@@ -0,0 +1,30 @@
...
+
+export const getSellers = async ( options : getSellersOptions , throwErr = true): Promise<ISeller[]> => {
+
+  if (!options.status) {
+    throw new ArgumentError('Missing args');
+  }
+
+  let sellersQuery: any = SellersCollection;
+
+  if (options.status) {
```
Comment (ariel-dao) [inline functions/src/payments/db/sellers/getSellers.ts:19]: remove this if, you are already checking this.

also move `let` to const

File: functions/src/payments/db/sellers/getSellers.ts [hunk 14]
```diff
@@ -0,0 +1,30 @@
...
+    sellersQuery = sellersQuery.where('status', '==', options.status);
+  }
+
+  try {
+    let sellers : ISeller[] = (await sellersQuery.get() as QuerySnapshot<ISeller>).docs.map(x => x.data());
```
Comment (ariel-dao) [inline functions/src/payments/db/sellers/getSellers.ts]: I don't think you need to cast to `QuerySnapshot<ISeller>`, it should be inferred from the seller collection query.

Comment (ariel-dao) [reply functions/src/payments/db/sellers/getSellers.ts]: also please avoid using names like "x" and write "seller" or doc instead

File: functions/src/payments/db/sellers/getSellers.ts [hunk 15]
```diff
@@ -0,0 +1,30 @@
...
+    return sellers;
+  } catch (e) {
+    if ( throwErr ) throw new CommonError('Could not get Sellers', e);
```
Comment (ariel-dao) [inline functions/src/payments/db/sellers/getSellers.ts:27]: else, log?

File: functions/src/payments/db/sellers/updateSeller.ts [hunk 16]
```diff
@@ -1,27 +1,48 @@
...
+        throw new CommonError('seller was updated, but could not attach uploaded document files to PAYME. error: ' + res.status_error_code + ' ' + res.status_error_details, {});
+    }
+  }
 
   return sellerDoc;
-};
\ No newline at end of file
+};
+
+const sortKeys = ( o : object ) => // returns new recursively sorted keys object
```
Comment (ariel-dao) [inline functions/src/payments/db/sellers/updateSeller.ts]: if you really want this function, it should be in the general util folder, not here

File: functions/src/payments/db/sellers/updateSeller.ts [hunk 17]
```diff
@@ -1,27 +1,48 @@
...
+  let sellerBefore : ISeller, sellerAfter : ISeller, docsSnapBefore : string = '', docsSnapAfter : string = ''
 
   try {
-    const res = await SellersCollection.where('userId', '==', userId).get();
-    await res.docs[0].ref.update(sellerDoc);
+    sellerBefore = await sellerDb.get( { userId } );
+    await db.collection(COLLECTIONS.Sellers).doc(sellerBefore.id).update(sellerDoc);
+    sellerAfter = { ...sellerBefore, ...sellerDoc }
+
+    if ( sellerBefore.bankAccountDetails?.identificationDocs) docsSnapBefore = JSON.stringify( sortKeys( sellerBefore.bankAccountDetails.identificationDocs ) )
```
Comment (ariel-dao) [inline functions/src/payments/db/sellers/updateSeller.ts]: you should move this entire functionality of equivalence to a util function and not run here as JSON.stringify

File: functions/src/payments/index.ts [hunk 18]
```diff
@@ -3,16 +3,18 @@ import * as functions from 'firebase-functions';
...
 const payments = commonRouter();
 
 import * as crons from './crons';
 
 payments.use('/payme', paymeRouter)
-
 payments.use('/payout-docs', payOutDocsRouter);
 payments.use('/bank-account-details', bankAccountDetailsRouter);
 
+// curl http://localhost:5003/common-dev-dea4e/us-central1/payments/test  -H 'Content-Type:application/json' -H 'authorization: {"uid":"user"}' -d '{}'
```
Comment (ariel-dao) [inline functions/src/payments/index.ts]: remove curl... add to postman.

File: functions/src/payments/index.ts [hunk 19]
```diff
@@ -3,16 +3,18 @@ import * as functions from 'firebase-functions';
...
+payments.post('/test', checkPendingSellerStatus)
```
Comment (ariel-dao) [inline functions/src/payments/index.ts]: ???

File: functions/src/proposals/services/create/createFunding.ts [hunk 20]
```diff
@@ -46,6 +48,11 @@ export const createFundingProposal = async (payload: CreateFundingProposalPayloa
 
     if (!bankAccountDetails) throw new CommonError("cant create funding proposal without bank account details", { payload })
 
+    const seller = await sellerDb.get( { userId: proposerId }, false )
+    if ( seller && seller.status == SELLER_STATUSES.REJECTED ) {
```
Comment (ariel-dao) [inline functions/src/proposals/services/create/createFunding.ts]: change to seller?.status == SELLER_STATUSES.REJECTED

**Review by ariel-dao — CHANGES_REQUESTED** [review]
change please

File: functions/src/payments/crons/checkPendingSellerStatus.ts (hunk 10 above)
Comment (noamso1) [reply functions/src/payments/crons/checkPendingSellerStatus.ts:51]: typescript does not allow this is a required field.

File: functions/src/payments/db/sellers/getSeller.ts (hunk 12 above)
Comment (noamso1) [reply functions/src/payments/db/sellers/getSeller.ts:25]: it did not return null and this caused the bug. should specifically return undefined.

File: functions/src/payments/db/sellers/getSellers.ts (hunk 13 above)
Comment (noamso1) [reply functions/src/payments/db/sellers/getSellers.ts:19]: i don't understand, and it's not a const.

File: functions/src/payments/db/sellers/getSellers.ts (hunk 14 above)
Comment (noamso1) [reply functions/src/payments/db/sellers/getSellers.ts]: changed x to "seller" in the map function. about the type - it is not inferred here because we are talking directly to the DB and not using a typed function.

File: functions/src/payments/business/payme/payOut/uploadSellerFiles.ts (hunk 7 above)
Comment (noamso1) [reply functions/src/payments/business/payme/payOut/uploadSellerFiles.ts:18]: payout log is per proposal and this func is for seller. we must have a proposal ID for it.

**Review by ariel-dao — APPROVED** [review]

**Review by ariel-dao — APPROVED** [review]

**Review by ariel-dao — APPROVED** [review]
